platform:ios,10.0

use_frameworks!
target:Memo do

pod 'Alamofire', '4.0.1'
pod 'SwiftyJSON', '3.1.0'
pod 'XCGLogger', '4.0.0'
pod 'KeychainAccess', '3.0.0'
pod 'IQKeyboardManagerSwift', '4.0.6'
pod 'Kingfisher', '3.1.3'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
pod 'FMDB', '2.6.2'
pod 'RESideMenu', '4.0.7'
pod 'UITableView+FDTemplateLayoutCell', '1.5.beta'

end
